# Generated by Django 3.1.2 on 2020-11-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mood', models.CharField(max_length=25)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=25)),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('timeSignature', models.IntegerField()),
                ('valence', models.FloatField()),
                ('duration', models.FloatField()),
                ('songKey', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('loudness', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('spotifyID', models.CharField(max_length=22)),
                ('popularity', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='userSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='playlistSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseModels.playlists')),
                ('songID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseModels.songs')),
            ],
        ),
        migrations.CreateModel(
            name='likedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('songID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseModels.songs')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
