# Generated by Django 3.1.2 on 2020-11-14 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idealSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=25)),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('timeSignature', models.IntegerField()),
                ('valence', models.FloatField()),
                ('duration', models.FloatField()),
                ('songKey', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('loudness', models.FloatField()),
                ('popularity', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
